name = "Weekend Wardy"
author = "AshAxolotl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c2ab7ad2b6971e409272443a8b5880ea69bb3811950cf6d5131b119c84d086b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
unsup = "1.1.5"

[options]
acceptable-game-versions = ["1.21", "1.21.0", "1.21.1"]
