name = "Weekend Wardy"
author = "AshAxolotl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41b9e4deb1bced99f616821d3b58f731b257d53184eaadc8f464cef844b25e7d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
unsup = "1.1.5"

[options]
acceptable-game-versions = ["1.21", "1.21.0", "1.21.1"]
