name = "Weekend Wardy"
author = "AshAxolotl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dccb579d2b4ccd569df22c5752615838949005c62e60a20710b50d9f377b91e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
unsup = "1.1.5"

[options]
acceptable-game-versions = ["1.21", "1.21.0", "1.21.1"]
