name = "Weekend Wardy"
author = "AshAxolotl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f765aee3e4211ff45639aa8553e2f74e9bdd63e5aa02138c991f8f1541a46b22"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
unsup = "1.1.5"

[options]
acceptable-game-versions = ["1.21", "1.21.0", "1.21.1"]
