name = "Weekend Wardy"
author = "AshAxolotl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d075a863ae0c188e490ffb6f3133067ce026bc66614cca4d62814cef29de2e21"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
unsup = "1.1.5"

[options]
acceptable-game-versions = ["1.21", "1.21.0", "1.21.1"]
