name = "Weekend Wardy"
author = "AshAxolotl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0525d6a20d4fb674e6f35543f473fbab0cd7afb92b8bf4c1c310a0558fd3735"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
unsup = "1.1.5"

[options]
acceptable-game-versions = ["1.21", "1.21.0", "1.21.1"]
